export const EVENT_TYPE_TIME_SPAN_CHANGE = 'EVENT_TYPE_TIME_SPAN_CHANGE'
export const BOTTOM_TAB_SELECT = 'BOTTOM_TAB_SELECT'
export const FAVORITE_CHANGED_POPULAR = 'FAVORITE_CHANGED_POPULAR'
export const FAVORITE_CHANGED_TRENDING = 'FAVORITE_CHANGED_TRENDING'
